services:
  - mysql
  - redis
jobs:
  include:
  - stage: PHP-7.3
    dist: bionic
    before_install:
      - sudo apt install -y software-properties-common
      - sudo add-apt-repository -y ppa:ondrej/php
      - sudo apt update
      - sudo apt install -y php7.3
    script:
      - php -v

  - stage: PHP-8.0
    dist: focal
    before_install:
      - sudo apt update
      - sudo apt upgrade
      - sudo apt install  ca-certificates apt-transport-https software-properties-common
      - sudo add-apt-repository -y ppa:ondrej/php
      - sudo apt install -y php8.0 libapache2-mod-php8.0
      - sudo systemctl restart apache2
    script:
      - php -v