services:
  - mysql
  - redis
language: php
jobs:
  include:
    - dist: focal
      before_install:
        - sudo apt update
        - sudo apt install  ca-certificates apt-transport-https software-properties-common
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt install -y php8.0 libapache2-mod-php8.0
        - sudo systemctl restart apache2
      script:
        - php -v