services:
  - mysql
  - redis
language: php
dist: bionic
before_install:
- sudo apt update
- sudo apt install -y ca-certificates apt-transport-https software-properties-common
- sudo add-apt-repository -y ppa:ondrej/php
- sudo apt install -y php8.0 libapache2-mod-php8.0
- sudo update-alternatives --config php
- sudo update-alternatives --set php /usr/bin/php8.0
script:
- php -v